### ISSUE TITLE
Disable "Edit Dimension" in embedded version?

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio-metavis-component#6]
I just tried to copy a dimension label in the embedded breve and noticed that the edit dimension window opens. Embedded should be considered 'presentation' with editing disabled. Unfortunately, opening the window also triggers some overlay that prevents closing the window without refreshing the page.

**Comment by esjewett** [comment]
Thanks for pointing this out. This should be fixed in 1.0.6. It should no longer trigger when the metavis is not set to be modifiable.

If you update your bower component palladio-metavis-component to 1.0.6, it should stop popping up.

**Comment by cncoleman** [comment]
Ethan,


To update, do I need to: 1. Edit this this to change the version number in /palladio/bower_components/bower.json; and 2. run Bower Update in bower_components?


Also, bower.json in the current site include both metaview and metavis. Can I remove metaview? Or does it matter? Thanks




  "dependencies": {
    "palladio": "^1.2.3",
    "palladio-timeline-component": "1.0.7",
    "palladio-facet-component": "^1.1.1",
    "palladio-timespan-component": "^1.1.0",
    "palladio-graph-component": "^1.0.1",
    "palladio-map-component": "^1.2.0",
    "palladio-table-component": "^1.1.2",
    "palladio-cards-component": "^1.0.2",
    "palladio-metaview-component": "^1.0.2",
    "palladio-metavis-component": "^1.0.5"
  },



________________________________
